# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- main
- release/*

pr:
- main
- release/*

strategy:
  matrix:
    jdk10_linux:
      imageName: "ubuntu-latest"
      jdk_version: "1.10"
    jdk11_windows:
      imageName: "vs2017-win2016"
      jdk_version: "1.11"
  maxParallel: 2

pool:
  vmImage: $(imageName)

steps:
- template: simple-param.yml
  parameters:
    yesNo: false
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: $(jdk_version)
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'package'

- task: PublishCodeCoverageResults@1
  inputs:
    codeCoverageTool: "JaCoCo"
    summaryFileLocation: "$(System.DefaultWorkingDirectory)/**/site/jacoco/jacoco.xml"
    reportDirectory: "$(System.DefaultWorkingDirectory)/**/site/jacoco"
    failIfCoverageEmpty: true

- task: NodeTool@0
  displayName: "Node install"
  inputs:
    versionSpec: '6.x' # The version we're installing
# Write the installed version to the command line
- script: which node